### ISSUE TITLE
Source code of the native module?

### ISSUE THREAD

**Issue by RubberDuckShobe** [LyffLyff/Veles#3]
Hello, I'd like to ask if there's any chance you could publish the source of the native parts of this? The VelesNative repo just seems to be the Godot module example.

**Comment by LyffLyff** [comment]
The "master" branch of the VelesNative Project is just a fork the example project to be able to make pull requests to the main project easily, but the "veles_native_dev" branch is the actual Native part of the Veles Project :)
[https://github.com/LyffLyff/VelesNative/tree/veles_native_dev](https://github.com/LyffLyff/VelesNative/tree/veles_native_dev)

**Comment by RubberDuckShobe** [comment]
I see, thank you!

**Comment by LyffLyff** [comment]
Glad I could help :)
